apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fastapi-app
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/MercierEva/fastapi-helm-argo.git'
    targetRevision: HEAD
    path: charts/fastapi-chart
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

