name: Build and Deploy FastAPI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ghcr.io/merciereva/fastapi:latest

      - name: Update Helm values.yaml with new image tag
        run: |
          sed -i "s|repository: .*|repository: ghcr.io/${{ github.repository_owner }}/fastapi|" charts/fastapi-chart/values.yaml
          sed -i "s|tag: .*|tag: latest|" charts/fastapi-chart/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/fastapi-chart/values.yaml
          git commit -m "Update Helm chart image tag to latest"
          git push https://x-access-token:${{ secrets.CR_PAT }}@github.com/${{ github.repository }}.git HEAD:main          
      

