name: CI/CD FastAPI Helm ArgoCD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ghcr.io/MercierEva
      CHART_PATH: charts/fastapi-chart
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u mercier --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=latest
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_TAG: latest

      - name: Update Helm chart with new image tag
        run: |
          sed -i "s|repository:.*|repository: $IMAGE_NAME|" $CHART_PATH/values.yaml
          sed -i "s|tag:.*|tag: latest|" $CHART_PATH/values.yaml

      - name: Commit and push updated Helm chart
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add $CHART_PATH/values.yaml || true
          git commit -m "Update Helm chart image tag to latest" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.CR_PAT }}@github.com/MercierEva/fastapi-helm-argo.git HEAD:main

